### ISSUE TITLE
Enhancement: Customize image thumbnails

### ISSUE THREAD

**Issue by arthur-wsw** [pinax/pinax-images#4]
For now there is now thumbnail options, 

Thumbnails are generated with following options defined in models but i didn't find a way to customize it.
- list_thumbnail: ImageSpecField([SmartResize(35, 35)], ...)
- small_thumbnail = ImageSpecField([SmartResize(100, 100)], ...)
- medium_thumbnail = ImageSpecField([SmartResize(400, 400)], ...)

For some project it's totally fine but for others we could want other thumbnail option (uncropped thumbnail for exemple). The only way to make this append properly for me is to add a variable to project settings

What are you thinking of this ?

For implementation, I'm looking for a way to make this possible without breaking the ImageKit generate_thumbnails command, is someone who know this ImageKit well has trick to make make this possible.

**Comment by paltman** [comment]
I'd love to figure out a way to have this set at the project level. Haven't spent much time thinking about it yet but I do know that ImageKit supports setting specs as named settings rather than how I did it.  Perhaps that is the best route to take.

**Comment by arthur-wsw** [comment]
I think i could find a way of doing and just want some opinions before trying to implement it.

Like it's explain in [the-imagespecfield-shorthand-syntax](http://django-imagekit.readthedocs.org/en/latest/advanced_usage.html#the-imagespecfield-shorthand-syntax) of imagekit, ImageSpecField is actually just shorthand for creating an ImageSpec, registering it, and associating it with an ImageSpecField.

With this in mind i'm think we could define 3 or 4 ImageSpec class : list_thumbnail, small_thumbnail, medium_thumbnail, thumbnail) with id attribute instead of processor, format and option and we could
1.  Let user override ImageSpec class and in settings provide extended class maybe the same way django did for user model 
2. Just let user call `register.generator('pinax_image:image:list_thumbnail', MyListThumbnail)` in his project with corresponding ID for each thumbnail.

Did you think i'm on the right way to do it ?
Between solution 1 and 2 which one is more in pinax way of doing ?

I think i could write some code to test this solution by the end of the week.

**Comment by paltman** [comment]
I think we want to go down the path of choice 1.

The way I envision this working is we add a setting that is a dotted notation to the `ImageSpec` class that we have defined as a default for each of the 4 sizes we want to provide. 

Then add an `apps.py` module and requisite hook up in `__init__.py` and define a `ready()` method in which we convert the dotted notation of each setting, to the imported objected (see [load_path_attr](https://github.com/pinax/pinax-teams/blob/master/pinax/teams/conf.py#L9) for the util function used to accomplish this), after doing that, still in the `ready()` method, call the `register.generator` method for each id that is on the model.  We should provide defaults so do something like:

``` python

from django.apps import AppConfig as BaseAppConfig
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

class AppConfig(BaseAppConfig):

    name = "pinax.images"
    label = "pinax_images"
    verbose_name = _("Pinax Images")

    def ready(self):
        list_thumbnail_path = getattr(settings, "PINAX_IMAGES_LIST_THUMBNAIL_SPEC", "pinax.images.specs.ListThumbnail")
        ListThumbnail = load_path_attr(list_thumbnail_path)
        register.generator("pinax_images:image:list_thumbnail", ListThumbnail)
```

I'm obviously missing some imports there and there _might_ be an issue with importing `django.conf.settings` in `apps.py`, but you'll quickly find out.  Also, you'll notice this adds a `specs.py` module to just keep things tidy instead of jamming them into `models.py`.

Thoughts?

**Comment by arthur-wsw** [comment]
I never used appconfig, so didn't know it was simple as that to add config for an app :)
You convince me that solution 1 is the way to go.

I'll think i'll try this today or tomorrow, and if it's work as expected i'll make a PR.
